app = "body-composition-scanner"
primary_region = "lhr"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8000"

[[services]]
internal_port = 8_000
processes = [ "app" ]
protocol = "tcp"

  [services.concurrency]
  hard_limit = 50
  soft_limit = 25
  type = "connections"

  [[services.ports]]
  handlers = [ "tls" ]
  port = 443

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "2gb"