[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50
  [[services.ports]]
    handlers = ["http"]
    port = 80
